### ISSUE TITLE
PvPManager compatibility

### ISSUE THREAD

**Issue by Royalphax** [Roytreo28/Revenge#3]
Something is wrong with PVPManager compatibility!
```
[06:04:25] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Revenge v6.7
java.lang.NoClassDefFoundError: me/NoChance/PvPManager/Config/Messages
at fr.roytreo.revenge.core.softdepend.PvPManager.get(PvPManager.java:26) ~[?:?]
at fr.roytreo.revenge.core.task.AggroTask.<init>(AggroTask.java:52) ~[?:?]
at fr.roytreo.revenge.core.event.entity.EntityDamageByEntity.onEntityDamageByEntity(EntityDamageByEntity.java:57) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1693.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1094]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:578) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) ~[patched_1.11.2.jar:git-Paper-1094]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:610) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1330) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:872) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1216) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1617) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1094]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1094]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1094]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Royalphax** [comment]
Done !
