### ISSUE TITLE
Error in 1.14.1

### ISSUE THREAD

**Issue by pmme** [Roytreo28/Revenge#7]
Getting the following loading Revenge-7.4.1.jar in spigot-1.14.1:

```[06:11:07] [Thread-8/WARN]: Exception in thread "Thread-8" 
[06:11:07] [Thread-8/WARN]: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getServerName()Ljava/lang/String;
[06:11:07] [Thread-8/WARN]: 	at fr.roytreo.revenge.core.stats.DataRegister$ServerNameData.getData(DataRegister.java:285)
[06:11:07] [Thread-8/WARN]: 	at fr.roytreo.revenge.core.stats.DataRegister$DataType.getData(DataRegister.java:202)
[06:11:07] [Thread-8/WARN]: 	at fr.roytreo.revenge.core.stats.DataRegister$DataType.access$2(DataRegister.java:199)
[06:11:07] [Thread-8/WARN]: 	at fr.roytreo.revenge.core.stats.DataRegister.connect(DataRegister.java:107)
[06:11:07] [Thread-8/WARN]: 	at fr.roytreo.revenge.core.stats.DataRegister.lambda$0(DataRegister.java:50)
[06:11:07] [Thread-8/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pmme** [comment]
I suppose you now need org.bukkit.Bukkit.getServer().getName()?

**Comment by thanosparavantis** [comment]
I can confirm this issue, same for me using 1.14.3.

**Comment by Royalphax** [comment]
That is now fixed! 👍 
Thanks for the report !
